baseURL = 'https://kxops.com'
locale = 'en-us'
title = 'kxops'
theme = 'PaperMod'

[[menu.main]]        
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "全部文章"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"  
  
   