baseURL = 'https://www.kxops.com'
locale = 'en-us'
title = 'kxops'
theme = 'PaperMod'

[params]
  mainSections = ["posts"]   

[params.assets]
  disableFingerprinting = true

disableKinds = ["taxonomy", "taxonomyTerm", "term", "RSS"]

[taxonomies]
  category = ""
  tag = ""

[[menu.main]]        
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/archives/" 
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/" 